# Generated by Django 3.2.18 on 2023-03-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
    ]
